### ISSUE TITLE
无参数启动

### ISSUE THREAD

**Issue by 14nmplus** [0382/argparse-f#9]
调用程序如果不传参，现在是直接退出，可以让它按照默认参数运行吗？

**Comment by 0382** [comment]
option是可选的，可以设置默认参数，命令行没有指定则get_option_xxx获得的就是默认参数；argument是必选的，没有默认参数，必须指定。你或许需要的是全部设置为option

**Comment by 0382** [comment]
好吧，好像写的逻辑确实是，如果没有指定参数，打印一个帮助信息。这在全option的情况是似乎确实不太合理
